inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'db/migrate/**'
  - 'config/**/*'
  - 'bin/**'
  - 'vendor/**/*'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false