version: '3'
services:
  db:
    image: postgres
    environment:  
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "3306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
    stdin_open: true  #デバッグで止めれる
    tty: true #デバッグで止めれる

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run serve
    ports: 
      - 8080:8080

volumes:
  postgresdata: